export const CenterStatusMap: { [key: string]: string } = {
    Active: 'Hoạt động',
    active: 'Hoạt động',
    Inactive: 'Tạm ngưng',
    inactive: 'Tạm ngưng',
    Pending: 'Đang chờ',
    pending: 'Đang chờ',
    Updating: 'Đang cập nhật',
    updating: 'Đang cập nhật',
    Suspended: 'Vi phạm',
    suspended: 'Vi phạm',
    Closed: 'Đóng cửa',
    closed: 'Đóng cửa',
    Rejected: 'Từ chối',
    rejected: 'Từ chối',
};
