export const CenterBadgeStatusMap: { [key: string]: string } = {
    Pending: 'default',
    pending: 'default',
    Active: 'green',
    active: 'green',
    Inactive: 'error',
    inactive: 'error',
    Updating: 'warning',
    updating: 'warning',
    Suspended: 'error',
    suspended: 'error',
    Closed: 'error',
    closed: 'error',
    Rejected: 'error',
    rejected: 'error',
};

export const CenterBadgeAntStatusMap: { [key: string]: string } = {
    Pending: 'gray',
    pending: 'gray',
    Active: 'green',
    active: 'green',
    Inactive: 'volcano',
    inactive: 'volcano',
    Updating: 'yellow',
    updating: 'yellow',
    Suspended: 'red',
    suspended: 'red',
    Closed: 'red',
    closed: 'red',
    Rejected: 'red',
    rejected: 'red',
};
